import os from 'os';
import crypto from 'crypto';

// MAC prefixes belonging to virtual/VPN/tunnel adapters (not physical hardware).
// The '02:' prefix catches locally-administered MACs generated by Docker, Hyper-V,
// WSL, VMware, VirtualBox, and most VPN clients.
const VIRTUAL_MAC_PREFIXES = [
  '02:',
  '00:00:00',
  'ff:ff:ff',
  'fe:80:',
];

// Adapter name patterns that indicate virtual/VPN/tunnel interfaces.
const VIRTUAL_NAME_PATTERNS: RegExp[] = [
  /vpn/i, /tun/i, /tap/i, /docker/i, /vbox/i, /vmware/i,
  /loopback/i, /virtual/i, /hyper-v/i, /wsl/i, /tunnel/i,
  /teredo/i, /isatap/i, /6to4/i,
];

function isVirtualAdapter(item: any): boolean {
  if (item.internal) return true;
  if (!item.mac || item.mac === '00:00:00:00:00:00') return true;

  const macLower = item.mac.toLowerCase();
  if (VIRTUAL_MAC_PREFIXES.some(prefix => macLower.startsWith(prefix))) return true;

  const name = item.name || '';
  if (VIRTUAL_NAME_PATTERNS.some(pattern => pattern.test(name))) return true;

  return false;
}

function getFilteredMacs(): string[] {
  const interfaces = os.networkInterfaces();
  if (!interfaces) return [];

  return Object.values(interfaces)
    .flat()
    .filter((item: any) => item != null && !isVirtualAdapter(item))
    .map((item: any) => item.mac)
    .sort();
}

function getAllNonInternalMacs(): string[] {
  const interfaces = os.networkInterfaces();
  if (!interfaces) return [];

  return Object.values(interfaces)
    .flat()
    .filter((item: any) => item != null && !item.internal && !!item.mac && item.mac !== '00:00:00:00:00:00')
    .map((item: any) => item.mac)
    .sort();
}

export function getMachineFingerprint(): string {
  const filteredMacs = getFilteredMacs();

  // If filtering removed all MACs, fall back to all non-internal MACs.
  // This handles unusual hardware where every NIC has a locally-administered MAC.
  const macs = filteredMacs.length > 0 ? filteredMacs : getAllNonInternalMacs();

  const raw = [
    os.hostname(),
    os.platform(),
    os.arch(),
    os.cpus()[0]?.model || '',
    macs.join('|'),
  ].join('::');

  return crypto.createHash('sha256').update(raw).digest('hex');
}

/**
 * Returns a fingerprint based only on stable hardware identifiers
 * (hostname, platform, architecture, CPU model) — no network information.
 * Used to detect "same physical machine" when MAC addresses change.
 */
export function getStableFingerprint(): string {
  const raw = [
    os.hostname(),
    os.platform(),
    os.arch(),
    os.cpus()[0]?.model || '',
  ].join('::');

  return crypto.createHash('sha256').update(raw).digest('hex');
}
