// Aliases de produtos: chave = como o cliente escreve, valor = nome exato no catálogo
// Para adicionar um novo alias, basta adicionar uma linha aqui
// Também é possível usar categorias genéricas (cerveja, vinho, etc.)

export const PRODUCT_ALIASES: Record<string, string> = {
  // === CERVEJAS ===
  'heineken': 'Heineken 600ml',
  'heineken 600': 'Heineken 600ml',
  'heineken garrafa': 'Heineken 600ml',
  'heineken long': 'Heineken Long Neck',
  'long neck': 'Heineken Long Neck',
  'long neck heineken': 'Heineken Long Neck',
  'heineken ln': 'Heineken Long Neck',
  'heiniken': 'Heineken 600ml',
  'hiniken': 'Heineken 600ml',
  'hainequen': 'Heineken 600ml',
  'haineken': 'Heineken 600ml',
  'heineken long neck': 'Heineken Long Neck',
  'skol': 'Skol 600ml',
  'skol 600': 'Skol 600ml',
  'skol garrafa': 'Skol 600ml',
  'skol 600ml': 'Skol 600ml',
  'brahma': 'Brahma 600ml',
  'brahma 600': 'Brahma 600ml',
  'brahma garrafa': 'Brahma 600ml',
  'brama': 'Brahma 600ml',
  'stella': 'Stella Artois 330ml',
  'stella artois': 'Stella Artois 330ml',
  'corona': 'Corona 355ml',
  'corona extra': 'Corona 355ml',
  'corona 355': 'Corona 355ml',
  'colorado': 'Colorado Appia 600ml',
  'appia': 'Colorado Appia 600ml',
  'colorado appia': 'Colorado Appia 600ml',
  'ipa': 'IPA Wals 600ml',
  'wals': 'IPA Wals 600ml',
  'ipa wals': 'IPA Wals 600ml',

  // === VINHOS ===
  'reservado': 'Vinho Tinto Reservado 750ml',
  'vinho tinto': 'Vinho Tinto Reservado 750ml',
  'tinto': 'Vinho Tinto Reservado 750ml',
  'chardonay': 'Vinho Branco Chardonay 750ml',
  'vinho branco': 'Vinho Branco Chardonay 750ml',
  'branco': 'Vinho Branco Chardonay 750ml',
  'rosé': 'Vinho Rosé 750ml',
  'rose': 'Vinho Rosé 750ml',
  'vinho rosé': 'Vinho Rosé 750ml',
  'vinho': 'Vinho Suave 750ml',
  'vinho suave': 'Vinho Suave 750ml',
  'suave': 'Vinho Suave 750ml',

  // === DESTILADOS ===
  'red label': 'Red Label 1L',
  'red': 'Red Label 1L',
  'johnnie red': 'Red Label 1L',
  'johnnie walker red': 'Red Label 1L',
  'black label': 'Black Label 1L',
  'black': 'Black Label 1L',
  'johnnie black': 'Black Label 1L',
  'johnnie walker black': 'Black Label 1L',
  'smirnoff': 'Smirnoff Vodka 1L',
  'vodka': 'Smirnoff Vodka 1L',
  'vodka smirnoff': 'Smirnoff Vodka 1L',
  'gin': 'Gin Tanqueray 750ml',
  'tanqueray': 'Gin Tanqueray 750ml',
  'gin tanqueray': 'Gin Tanqueray 750ml',
  'cachaça': 'Cachaça 51 1L',
  'cachaca': 'Cachaça 51 1L',
  '51': 'Cachaça 51 1L',
  'whisky': 'Red Label 1L',
  'whiskey': 'Red Label 1L',

  // === SEM ÁLCOOL ===
  'coca': 'Coca-Cola 2L',
  'coca cola': 'Coca-Cola 2L',
  'cocacola': 'Coca-Cola 2L',
  'coca-cola': 'Coca-Cola 2L',
  'coca 2l': 'Coca-Cola 2L',
  'coca zero': 'Coca Cola Zero',
  'coca-cola zero': 'Coca Cola Zero',
  'zero': 'Coca Cola Zero',
  'guaraná': 'Guaraná Antarctica 2L',
  'guarana': 'Guaraná Antarctica 2L',
  'guaraná 2l': 'Guaraná Antarctica 2L',
  'guaraná antarctica': 'Guaraná Antarctica 2L',
  'refri': 'Coca-Cola 2L',
  'refrigerante': 'Coca-Cola 2L',
  'água': 'Água Mineral 500ml',
  'agua': 'Água Mineral 500ml',
  'água mineral': 'Água Mineral 500ml',
  'suco': 'Suco Del Valle 1L',
  'del valle': 'Suco Del Valle 1L',
  'suco del valle': 'Suco Del Valle 1L',

  // === PETISCOS ===
  'amendoim': 'Amendoim 200g',
  'batata': 'Batata Frita',
  'batata frita': 'Batata Frita',
  'fritas': 'Batata Frita',
  'isca': 'Isca de Frango',
  'frango': 'Isca de Frango',
  'isca de frango': 'Isca de Frango',
  'petisco': 'Batata Frita',
  'petiscos': 'Batata Frita',
  'lanche': 'Batata Frita',
};

// Categorias genéricas: quando o cliente diz "cerveja", mostra essas opções
export const CATEGORY_SUGGESTIONS: Record<string, string[]> = {
  'cerveja': ['Heineken Long Neck', 'Brahma 600ml', 'Corona 355ml'],
  'cervejas': ['Heineken Long Neck', 'Brahma 600ml', 'Corona 355ml'],
  'vinho': ['Vinho Tinto Reservado 750ml', 'Vinho Rosé 750ml', 'Vinho Suave 750ml'],
  'vinhos': ['Vinho Tinto Reservado 750ml', 'Vinho Rosé 750ml', 'Vinho Suave 750ml'],
  'whisky': ['Red Label 1L', 'Black Label 1L'],
  'whiskey': ['Red Label 1L', 'Black Label 1L'],
  'destilado': ['Red Label 1L', 'Smirnoff Vodka 1L', 'Gin Tanqueray 750ml'],
  'destilados': ['Red Label 1L', 'Smirnoff Vodka 1L', 'Gin Tanqueray 750ml'],
  'vodka': ['Smirnoff Vodka 1L'],
  'gin': ['Gin Tanqueray 750ml'],
  'cachaça': ['Cachaça 51 1L'],
  'cachaca': ['Cachaça 51 1L'],
  'refrigerante': ['Coca-Cola 2L', 'Guaraná Antarctica 2L'],
  'refri': ['Coca-Cola 2L', 'Guaraná Antarctica 2L'],
  'suco': ['Suco Del Valle 1L'],
  'petisco': ['Batata Frita', 'Amendoim 200g', 'Isca de Frango'],
  'petiscos': ['Batata Frita', 'Amendoim 200g', 'Isca de Frango'],
  'comida': ['Batata Frita', 'Amendoim 200g', 'Isca de Frango'],
  'comer': ['Batata Frita', 'Amendoim 200g', 'Isca de Frango'],
};

// Palavras que devem ser ignoradas ao processar (stopwords)
export const STOP_WORDS = [
  'de', 'do', 'da', 'dos', 'das', 'um', 'uma', 'uns', 'umas',
  'o', 'a', 'os', 'as', 'para', 'por', 'com', 'sem', 'em',
  'no', 'na', 'nos', 'nas', 'ao', 'à', 'e', 'ou', 'mas',
  'que', 'se', 'eu', 'me', 'minha', 'meu', 'te', 'ti',
  'quero', 'queria', 'queres', 'quer', 'pedir', 'pedido',
  'me vê', 'me da', 'pode ser', 'vou querer', 'vou levar',
  'também', 'tbm', 'mais', 'outro', 'outra', 'outros', 'outras',
  'o que', 'qual', 'quais', 'quanto', 'quanta',
];

// Frases de intenção
export const INTENT_KEYWORDS: Record<string, string[]> = {
  cardapio: ['cardápio', 'cardapio', 'menu', 'produtos', 'o que tem', 'oque tem'],
  acompanhar: ['meu pedido', 'status', 'acompanhar', 'onde está', 'onde esta', 'tá pronto', 'ta pronto'],
  cancelar: ['cancelar', 'cancela', 'desistir', 'desisto'],
  promocao: ['promoção', 'promocao', 'promo', 'oferta', 'desconto', 'promoções', 'promocoes'],
  ajuda: ['ajuda', 'help', 'como funciona', 'como faço'],
  pedir: ['quero', 'pedir', 'pedido', 'me vê', 'me da', 'vou querer', 'vou levar', 'queria'],
};
